# Generated by Django 2.2.5 on 2019-11-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0002_experiment_samples_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='desc_html',
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='affiliations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='authors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='funders',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='license',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='publisher',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='title',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
