# Generated by Django 2.2.5 on 2019-12-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0002_auto_20191122_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
