# Generated by Django 3.0.3 on 2020-03-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='url_template',
            field=models.URLField(null=True),
        ),
    ]
