# Generated by Django 2.2.5 on 2019-09-06 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossRefDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Cross Reference Database',
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrezid', models.IntegerField(db_index=True, null=True, unique=True)),
                ('systematic_name', models.CharField(db_index=True, max_length=32)),
                ('standard_name', models.CharField(db_index=True, max_length=32, null=True)),
                ('description', models.TextField()),
                ('aliases', models.TextField()),
                ('obsolete', models.BooleanField(default=False)),
                ('weight', models.FloatField(default=1)),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisms.Organism')),
            ],
        ),
        migrations.CreateModel(
            name='CrossRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xrid', models.CharField(db_index=True, max_length=32)),
                ('crossrefdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.CrossRefDB')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.Gene')),
            ],
        ),
    ]
